// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/request/payload/feed/feed-requests.proto

#ifndef PROTOBUF_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto__INCLUDED
#define PROTOBUF_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)

namespace protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsValidityPeriodImpl();
void InitDefaultsValidityPeriod();
void InitDefaultsMessageQueryImpl();
void InitDefaultsMessageQuery();
void InitDefaultsMessageConfirmImpl();
void InitDefaultsMessageConfirm();
void InitDefaultsMessageDeleteImpl();
void InitDefaultsMessageDelete();
inline void InitDefaults() {
  InitDefaultsValidityPeriod();
  InitDefaultsMessageQuery();
  InitDefaultsMessageConfirm();
  InitDefaultsMessageDelete();
}
}  // namespace protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto
namespace agrirouter {
namespace feed {
namespace request {
class MessageConfirm;
class MessageConfirmDefaultTypeInternal;
extern MessageConfirmDefaultTypeInternal _MessageConfirm_default_instance_;
class MessageDelete;
class MessageDeleteDefaultTypeInternal;
extern MessageDeleteDefaultTypeInternal _MessageDelete_default_instance_;
class MessageQuery;
class MessageQueryDefaultTypeInternal;
extern MessageQueryDefaultTypeInternal _MessageQuery_default_instance_;
class ValidityPeriod;
class ValidityPeriodDefaultTypeInternal;
extern ValidityPeriodDefaultTypeInternal _ValidityPeriod_default_instance_;
}  // namespace request
}  // namespace feed
}  // namespace agrirouter
namespace agrirouter {
namespace feed {
namespace request {

// ===================================================================

class ValidityPeriod : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.feed.request.ValidityPeriod) */ {
 public:
  ValidityPeriod();
  virtual ~ValidityPeriod();

  ValidityPeriod(const ValidityPeriod& from);

  inline ValidityPeriod& operator=(const ValidityPeriod& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ValidityPeriod(ValidityPeriod&& from) noexcept
    : ValidityPeriod() {
    *this = ::std::move(from);
  }

  inline ValidityPeriod& operator=(ValidityPeriod&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ValidityPeriod& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ValidityPeriod* internal_default_instance() {
    return reinterpret_cast<const ValidityPeriod*>(
               &_ValidityPeriod_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ValidityPeriod* other);
  friend void swap(ValidityPeriod& a, ValidityPeriod& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ValidityPeriod* New() const PROTOBUF_FINAL { return New(NULL); }

  ValidityPeriod* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ValidityPeriod& from);
  void MergeFrom(const ValidityPeriod& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ValidityPeriod* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.Timestamp sentFrom = 1;
  bool has_sentfrom() const;
  void clear_sentfrom();
  static const int kSentFromFieldNumber = 1;
  const ::google::protobuf::Timestamp& sentfrom() const;
  ::google::protobuf::Timestamp* release_sentfrom();
  ::google::protobuf::Timestamp* mutable_sentfrom();
  void set_allocated_sentfrom(::google::protobuf::Timestamp* sentfrom);

  // .google.protobuf.Timestamp sentTo = 2;
  bool has_sentto() const;
  void clear_sentto();
  static const int kSentToFieldNumber = 2;
  const ::google::protobuf::Timestamp& sentto() const;
  ::google::protobuf::Timestamp* release_sentto();
  ::google::protobuf::Timestamp* mutable_sentto();
  void set_allocated_sentto(::google::protobuf::Timestamp* sentto);

  // @@protoc_insertion_point(class_scope:agrirouter.feed.request.ValidityPeriod)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::Timestamp* sentfrom_;
  ::google::protobuf::Timestamp* sentto_;
  mutable int _cached_size_;
  friend struct ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::TableStruct;
  friend void ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::InitDefaultsValidityPeriodImpl();
};
// -------------------------------------------------------------------

class MessageQuery : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.feed.request.MessageQuery) */ {
 public:
  MessageQuery();
  virtual ~MessageQuery();

  MessageQuery(const MessageQuery& from);

  inline MessageQuery& operator=(const MessageQuery& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageQuery(MessageQuery&& from) noexcept
    : MessageQuery() {
    *this = ::std::move(from);
  }

  inline MessageQuery& operator=(MessageQuery&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageQuery& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageQuery* internal_default_instance() {
    return reinterpret_cast<const MessageQuery*>(
               &_MessageQuery_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MessageQuery* other);
  friend void swap(MessageQuery& a, MessageQuery& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageQuery* New() const PROTOBUF_FINAL { return New(NULL); }

  MessageQuery* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MessageQuery& from);
  void MergeFrom(const MessageQuery& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MessageQuery* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string message_ids = 1;
  int message_ids_size() const;
  void clear_message_ids();
  static const int kMessageIdsFieldNumber = 1;
  const ::std::string& message_ids(int index) const;
  ::std::string* mutable_message_ids(int index);
  void set_message_ids(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_message_ids(int index, ::std::string&& value);
  #endif
  void set_message_ids(int index, const char* value);
  void set_message_ids(int index, const char* value, size_t size);
  ::std::string* add_message_ids();
  void add_message_ids(const ::std::string& value);
  #if LANG_CXX11
  void add_message_ids(::std::string&& value);
  #endif
  void add_message_ids(const char* value);
  void add_message_ids(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& message_ids() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_message_ids();

  // repeated string senders = 2;
  int senders_size() const;
  void clear_senders();
  static const int kSendersFieldNumber = 2;
  const ::std::string& senders(int index) const;
  ::std::string* mutable_senders(int index);
  void set_senders(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_senders(int index, ::std::string&& value);
  #endif
  void set_senders(int index, const char* value);
  void set_senders(int index, const char* value, size_t size);
  ::std::string* add_senders();
  void add_senders(const ::std::string& value);
  #if LANG_CXX11
  void add_senders(::std::string&& value);
  #endif
  void add_senders(const char* value);
  void add_senders(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& senders() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_senders();

  // .agrirouter.feed.request.ValidityPeriod validity_period = 3;
  bool has_validity_period() const;
  void clear_validity_period();
  static const int kValidityPeriodFieldNumber = 3;
  const ::agrirouter::feed::request::ValidityPeriod& validity_period() const;
  ::agrirouter::feed::request::ValidityPeriod* release_validity_period();
  ::agrirouter::feed::request::ValidityPeriod* mutable_validity_period();
  void set_allocated_validity_period(::agrirouter::feed::request::ValidityPeriod* validity_period);

  // @@protoc_insertion_point(class_scope:agrirouter.feed.request.MessageQuery)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> message_ids_;
  ::google::protobuf::RepeatedPtrField< ::std::string> senders_;
  ::agrirouter::feed::request::ValidityPeriod* validity_period_;
  mutable int _cached_size_;
  friend struct ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::TableStruct;
  friend void ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::InitDefaultsMessageQueryImpl();
};
// -------------------------------------------------------------------

class MessageConfirm : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.feed.request.MessageConfirm) */ {
 public:
  MessageConfirm();
  virtual ~MessageConfirm();

  MessageConfirm(const MessageConfirm& from);

  inline MessageConfirm& operator=(const MessageConfirm& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageConfirm(MessageConfirm&& from) noexcept
    : MessageConfirm() {
    *this = ::std::move(from);
  }

  inline MessageConfirm& operator=(MessageConfirm&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageConfirm& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageConfirm* internal_default_instance() {
    return reinterpret_cast<const MessageConfirm*>(
               &_MessageConfirm_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(MessageConfirm* other);
  friend void swap(MessageConfirm& a, MessageConfirm& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageConfirm* New() const PROTOBUF_FINAL { return New(NULL); }

  MessageConfirm* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MessageConfirm& from);
  void MergeFrom(const MessageConfirm& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MessageConfirm* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string message_ids = 1;
  int message_ids_size() const;
  void clear_message_ids();
  static const int kMessageIdsFieldNumber = 1;
  const ::std::string& message_ids(int index) const;
  ::std::string* mutable_message_ids(int index);
  void set_message_ids(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_message_ids(int index, ::std::string&& value);
  #endif
  void set_message_ids(int index, const char* value);
  void set_message_ids(int index, const char* value, size_t size);
  ::std::string* add_message_ids();
  void add_message_ids(const ::std::string& value);
  #if LANG_CXX11
  void add_message_ids(::std::string&& value);
  #endif
  void add_message_ids(const char* value);
  void add_message_ids(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& message_ids() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_message_ids();

  // @@protoc_insertion_point(class_scope:agrirouter.feed.request.MessageConfirm)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> message_ids_;
  mutable int _cached_size_;
  friend struct ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::TableStruct;
  friend void ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::InitDefaultsMessageConfirmImpl();
};
// -------------------------------------------------------------------

class MessageDelete : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.feed.request.MessageDelete) */ {
 public:
  MessageDelete();
  virtual ~MessageDelete();

  MessageDelete(const MessageDelete& from);

  inline MessageDelete& operator=(const MessageDelete& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageDelete(MessageDelete&& from) noexcept
    : MessageDelete() {
    *this = ::std::move(from);
  }

  inline MessageDelete& operator=(MessageDelete&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageDelete& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageDelete* internal_default_instance() {
    return reinterpret_cast<const MessageDelete*>(
               &_MessageDelete_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(MessageDelete* other);
  friend void swap(MessageDelete& a, MessageDelete& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageDelete* New() const PROTOBUF_FINAL { return New(NULL); }

  MessageDelete* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MessageDelete& from);
  void MergeFrom(const MessageDelete& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MessageDelete* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string message_ids = 1;
  int message_ids_size() const;
  void clear_message_ids();
  static const int kMessageIdsFieldNumber = 1;
  const ::std::string& message_ids(int index) const;
  ::std::string* mutable_message_ids(int index);
  void set_message_ids(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_message_ids(int index, ::std::string&& value);
  #endif
  void set_message_ids(int index, const char* value);
  void set_message_ids(int index, const char* value, size_t size);
  ::std::string* add_message_ids();
  void add_message_ids(const ::std::string& value);
  #if LANG_CXX11
  void add_message_ids(::std::string&& value);
  #endif
  void add_message_ids(const char* value);
  void add_message_ids(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& message_ids() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_message_ids();

  // repeated string senders = 2;
  int senders_size() const;
  void clear_senders();
  static const int kSendersFieldNumber = 2;
  const ::std::string& senders(int index) const;
  ::std::string* mutable_senders(int index);
  void set_senders(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_senders(int index, ::std::string&& value);
  #endif
  void set_senders(int index, const char* value);
  void set_senders(int index, const char* value, size_t size);
  ::std::string* add_senders();
  void add_senders(const ::std::string& value);
  #if LANG_CXX11
  void add_senders(::std::string&& value);
  #endif
  void add_senders(const char* value);
  void add_senders(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& senders() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_senders();

  // .agrirouter.feed.request.ValidityPeriod validity_period = 3;
  bool has_validity_period() const;
  void clear_validity_period();
  static const int kValidityPeriodFieldNumber = 3;
  const ::agrirouter::feed::request::ValidityPeriod& validity_period() const;
  ::agrirouter::feed::request::ValidityPeriod* release_validity_period();
  ::agrirouter::feed::request::ValidityPeriod* mutable_validity_period();
  void set_allocated_validity_period(::agrirouter::feed::request::ValidityPeriod* validity_period);

  // @@protoc_insertion_point(class_scope:agrirouter.feed.request.MessageDelete)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> message_ids_;
  ::google::protobuf::RepeatedPtrField< ::std::string> senders_;
  ::agrirouter::feed::request::ValidityPeriod* validity_period_;
  mutable int _cached_size_;
  friend struct ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::TableStruct;
  friend void ::protobuf_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto::InitDefaultsMessageDeleteImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ValidityPeriod

// .google.protobuf.Timestamp sentFrom = 1;
inline bool ValidityPeriod::has_sentfrom() const {
  return this != internal_default_instance() && sentfrom_ != NULL;
}
inline const ::google::protobuf::Timestamp& ValidityPeriod::sentfrom() const {
  const ::google::protobuf::Timestamp* p = sentfrom_;
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.ValidityPeriod.sentFrom)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* ValidityPeriod::release_sentfrom() {
  // @@protoc_insertion_point(field_release:agrirouter.feed.request.ValidityPeriod.sentFrom)
  
  ::google::protobuf::Timestamp* temp = sentfrom_;
  sentfrom_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* ValidityPeriod::mutable_sentfrom() {
  
  if (sentfrom_ == NULL) {
    sentfrom_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.ValidityPeriod.sentFrom)
  return sentfrom_;
}
inline void ValidityPeriod::set_allocated_sentfrom(::google::protobuf::Timestamp* sentfrom) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(sentfrom_);
  }
  if (sentfrom) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast< ::google::protobuf::MessageLite*>(sentfrom)->GetArena();
    if (message_arena != submessage_arena) {
      sentfrom = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sentfrom, submessage_arena);
    }
    
  } else {
    
  }
  sentfrom_ = sentfrom;
  // @@protoc_insertion_point(field_set_allocated:agrirouter.feed.request.ValidityPeriod.sentFrom)
}

// .google.protobuf.Timestamp sentTo = 2;
inline bool ValidityPeriod::has_sentto() const {
  return this != internal_default_instance() && sentto_ != NULL;
}
inline const ::google::protobuf::Timestamp& ValidityPeriod::sentto() const {
  const ::google::protobuf::Timestamp* p = sentto_;
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.ValidityPeriod.sentTo)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* ValidityPeriod::release_sentto() {
  // @@protoc_insertion_point(field_release:agrirouter.feed.request.ValidityPeriod.sentTo)
  
  ::google::protobuf::Timestamp* temp = sentto_;
  sentto_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* ValidityPeriod::mutable_sentto() {
  
  if (sentto_ == NULL) {
    sentto_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.ValidityPeriod.sentTo)
  return sentto_;
}
inline void ValidityPeriod::set_allocated_sentto(::google::protobuf::Timestamp* sentto) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(sentto_);
  }
  if (sentto) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast< ::google::protobuf::MessageLite*>(sentto)->GetArena();
    if (message_arena != submessage_arena) {
      sentto = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sentto, submessage_arena);
    }
    
  } else {
    
  }
  sentto_ = sentto;
  // @@protoc_insertion_point(field_set_allocated:agrirouter.feed.request.ValidityPeriod.sentTo)
}

// -------------------------------------------------------------------

// MessageQuery

// repeated string message_ids = 1;
inline int MessageQuery::message_ids_size() const {
  return message_ids_.size();
}
inline void MessageQuery::clear_message_ids() {
  message_ids_.Clear();
}
inline const ::std::string& MessageQuery::message_ids(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.MessageQuery.message_ids)
  return message_ids_.Get(index);
}
inline ::std::string* MessageQuery::mutable_message_ids(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.MessageQuery.message_ids)
  return message_ids_.Mutable(index);
}
inline void MessageQuery::set_message_ids(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageQuery.message_ids)
  message_ids_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MessageQuery::set_message_ids(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageQuery.message_ids)
  message_ids_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MessageQuery::set_message_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  message_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.feed.request.MessageQuery.message_ids)
}
inline void MessageQuery::set_message_ids(int index, const char* value, size_t size) {
  message_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.feed.request.MessageQuery.message_ids)
}
inline ::std::string* MessageQuery::add_message_ids() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.feed.request.MessageQuery.message_ids)
  return message_ids_.Add();
}
inline void MessageQuery::add_message_ids(const ::std::string& value) {
  message_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageQuery.message_ids)
}
#if LANG_CXX11
inline void MessageQuery::add_message_ids(::std::string&& value) {
  message_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageQuery.message_ids)
}
#endif
inline void MessageQuery::add_message_ids(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  message_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.feed.request.MessageQuery.message_ids)
}
inline void MessageQuery::add_message_ids(const char* value, size_t size) {
  message_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.feed.request.MessageQuery.message_ids)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MessageQuery::message_ids() const {
  // @@protoc_insertion_point(field_list:agrirouter.feed.request.MessageQuery.message_ids)
  return message_ids_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MessageQuery::mutable_message_ids() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.feed.request.MessageQuery.message_ids)
  return &message_ids_;
}

// repeated string senders = 2;
inline int MessageQuery::senders_size() const {
  return senders_.size();
}
inline void MessageQuery::clear_senders() {
  senders_.Clear();
}
inline const ::std::string& MessageQuery::senders(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.MessageQuery.senders)
  return senders_.Get(index);
}
inline ::std::string* MessageQuery::mutable_senders(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.MessageQuery.senders)
  return senders_.Mutable(index);
}
inline void MessageQuery::set_senders(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageQuery.senders)
  senders_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MessageQuery::set_senders(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageQuery.senders)
  senders_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MessageQuery::set_senders(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  senders_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.feed.request.MessageQuery.senders)
}
inline void MessageQuery::set_senders(int index, const char* value, size_t size) {
  senders_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.feed.request.MessageQuery.senders)
}
inline ::std::string* MessageQuery::add_senders() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.feed.request.MessageQuery.senders)
  return senders_.Add();
}
inline void MessageQuery::add_senders(const ::std::string& value) {
  senders_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageQuery.senders)
}
#if LANG_CXX11
inline void MessageQuery::add_senders(::std::string&& value) {
  senders_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageQuery.senders)
}
#endif
inline void MessageQuery::add_senders(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  senders_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.feed.request.MessageQuery.senders)
}
inline void MessageQuery::add_senders(const char* value, size_t size) {
  senders_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.feed.request.MessageQuery.senders)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MessageQuery::senders() const {
  // @@protoc_insertion_point(field_list:agrirouter.feed.request.MessageQuery.senders)
  return senders_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MessageQuery::mutable_senders() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.feed.request.MessageQuery.senders)
  return &senders_;
}

// .agrirouter.feed.request.ValidityPeriod validity_period = 3;
inline bool MessageQuery::has_validity_period() const {
  return this != internal_default_instance() && validity_period_ != NULL;
}
inline void MessageQuery::clear_validity_period() {
  if (GetArenaNoVirtual() == NULL && validity_period_ != NULL) {
    delete validity_period_;
  }
  validity_period_ = NULL;
}
inline const ::agrirouter::feed::request::ValidityPeriod& MessageQuery::validity_period() const {
  const ::agrirouter::feed::request::ValidityPeriod* p = validity_period_;
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.MessageQuery.validity_period)
  return p != NULL ? *p : *reinterpret_cast<const ::agrirouter::feed::request::ValidityPeriod*>(
      &::agrirouter::feed::request::_ValidityPeriod_default_instance_);
}
inline ::agrirouter::feed::request::ValidityPeriod* MessageQuery::release_validity_period() {
  // @@protoc_insertion_point(field_release:agrirouter.feed.request.MessageQuery.validity_period)
  
  ::agrirouter::feed::request::ValidityPeriod* temp = validity_period_;
  validity_period_ = NULL;
  return temp;
}
inline ::agrirouter::feed::request::ValidityPeriod* MessageQuery::mutable_validity_period() {
  
  if (validity_period_ == NULL) {
    validity_period_ = new ::agrirouter::feed::request::ValidityPeriod;
  }
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.MessageQuery.validity_period)
  return validity_period_;
}
inline void MessageQuery::set_allocated_validity_period(::agrirouter::feed::request::ValidityPeriod* validity_period) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete validity_period_;
  }
  if (validity_period) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      validity_period = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, validity_period, submessage_arena);
    }
    
  } else {
    
  }
  validity_period_ = validity_period;
  // @@protoc_insertion_point(field_set_allocated:agrirouter.feed.request.MessageQuery.validity_period)
}

// -------------------------------------------------------------------

// MessageConfirm

// repeated string message_ids = 1;
inline int MessageConfirm::message_ids_size() const {
  return message_ids_.size();
}
inline void MessageConfirm::clear_message_ids() {
  message_ids_.Clear();
}
inline const ::std::string& MessageConfirm::message_ids(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.MessageConfirm.message_ids)
  return message_ids_.Get(index);
}
inline ::std::string* MessageConfirm::mutable_message_ids(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.MessageConfirm.message_ids)
  return message_ids_.Mutable(index);
}
inline void MessageConfirm::set_message_ids(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageConfirm.message_ids)
  message_ids_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MessageConfirm::set_message_ids(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageConfirm.message_ids)
  message_ids_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MessageConfirm::set_message_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  message_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.feed.request.MessageConfirm.message_ids)
}
inline void MessageConfirm::set_message_ids(int index, const char* value, size_t size) {
  message_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.feed.request.MessageConfirm.message_ids)
}
inline ::std::string* MessageConfirm::add_message_ids() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.feed.request.MessageConfirm.message_ids)
  return message_ids_.Add();
}
inline void MessageConfirm::add_message_ids(const ::std::string& value) {
  message_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageConfirm.message_ids)
}
#if LANG_CXX11
inline void MessageConfirm::add_message_ids(::std::string&& value) {
  message_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageConfirm.message_ids)
}
#endif
inline void MessageConfirm::add_message_ids(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  message_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.feed.request.MessageConfirm.message_ids)
}
inline void MessageConfirm::add_message_ids(const char* value, size_t size) {
  message_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.feed.request.MessageConfirm.message_ids)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MessageConfirm::message_ids() const {
  // @@protoc_insertion_point(field_list:agrirouter.feed.request.MessageConfirm.message_ids)
  return message_ids_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MessageConfirm::mutable_message_ids() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.feed.request.MessageConfirm.message_ids)
  return &message_ids_;
}

// -------------------------------------------------------------------

// MessageDelete

// repeated string message_ids = 1;
inline int MessageDelete::message_ids_size() const {
  return message_ids_.size();
}
inline void MessageDelete::clear_message_ids() {
  message_ids_.Clear();
}
inline const ::std::string& MessageDelete::message_ids(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.MessageDelete.message_ids)
  return message_ids_.Get(index);
}
inline ::std::string* MessageDelete::mutable_message_ids(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.MessageDelete.message_ids)
  return message_ids_.Mutable(index);
}
inline void MessageDelete::set_message_ids(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageDelete.message_ids)
  message_ids_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MessageDelete::set_message_ids(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageDelete.message_ids)
  message_ids_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MessageDelete::set_message_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  message_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.feed.request.MessageDelete.message_ids)
}
inline void MessageDelete::set_message_ids(int index, const char* value, size_t size) {
  message_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.feed.request.MessageDelete.message_ids)
}
inline ::std::string* MessageDelete::add_message_ids() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.feed.request.MessageDelete.message_ids)
  return message_ids_.Add();
}
inline void MessageDelete::add_message_ids(const ::std::string& value) {
  message_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageDelete.message_ids)
}
#if LANG_CXX11
inline void MessageDelete::add_message_ids(::std::string&& value) {
  message_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageDelete.message_ids)
}
#endif
inline void MessageDelete::add_message_ids(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  message_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.feed.request.MessageDelete.message_ids)
}
inline void MessageDelete::add_message_ids(const char* value, size_t size) {
  message_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.feed.request.MessageDelete.message_ids)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MessageDelete::message_ids() const {
  // @@protoc_insertion_point(field_list:agrirouter.feed.request.MessageDelete.message_ids)
  return message_ids_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MessageDelete::mutable_message_ids() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.feed.request.MessageDelete.message_ids)
  return &message_ids_;
}

// repeated string senders = 2;
inline int MessageDelete::senders_size() const {
  return senders_.size();
}
inline void MessageDelete::clear_senders() {
  senders_.Clear();
}
inline const ::std::string& MessageDelete::senders(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.MessageDelete.senders)
  return senders_.Get(index);
}
inline ::std::string* MessageDelete::mutable_senders(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.MessageDelete.senders)
  return senders_.Mutable(index);
}
inline void MessageDelete::set_senders(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageDelete.senders)
  senders_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MessageDelete::set_senders(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:agrirouter.feed.request.MessageDelete.senders)
  senders_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MessageDelete::set_senders(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  senders_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.feed.request.MessageDelete.senders)
}
inline void MessageDelete::set_senders(int index, const char* value, size_t size) {
  senders_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.feed.request.MessageDelete.senders)
}
inline ::std::string* MessageDelete::add_senders() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.feed.request.MessageDelete.senders)
  return senders_.Add();
}
inline void MessageDelete::add_senders(const ::std::string& value) {
  senders_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageDelete.senders)
}
#if LANG_CXX11
inline void MessageDelete::add_senders(::std::string&& value) {
  senders_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:agrirouter.feed.request.MessageDelete.senders)
}
#endif
inline void MessageDelete::add_senders(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  senders_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.feed.request.MessageDelete.senders)
}
inline void MessageDelete::add_senders(const char* value, size_t size) {
  senders_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.feed.request.MessageDelete.senders)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MessageDelete::senders() const {
  // @@protoc_insertion_point(field_list:agrirouter.feed.request.MessageDelete.senders)
  return senders_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MessageDelete::mutable_senders() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.feed.request.MessageDelete.senders)
  return &senders_;
}

// .agrirouter.feed.request.ValidityPeriod validity_period = 3;
inline bool MessageDelete::has_validity_period() const {
  return this != internal_default_instance() && validity_period_ != NULL;
}
inline void MessageDelete::clear_validity_period() {
  if (GetArenaNoVirtual() == NULL && validity_period_ != NULL) {
    delete validity_period_;
  }
  validity_period_ = NULL;
}
inline const ::agrirouter::feed::request::ValidityPeriod& MessageDelete::validity_period() const {
  const ::agrirouter::feed::request::ValidityPeriod* p = validity_period_;
  // @@protoc_insertion_point(field_get:agrirouter.feed.request.MessageDelete.validity_period)
  return p != NULL ? *p : *reinterpret_cast<const ::agrirouter::feed::request::ValidityPeriod*>(
      &::agrirouter::feed::request::_ValidityPeriod_default_instance_);
}
inline ::agrirouter::feed::request::ValidityPeriod* MessageDelete::release_validity_period() {
  // @@protoc_insertion_point(field_release:agrirouter.feed.request.MessageDelete.validity_period)
  
  ::agrirouter::feed::request::ValidityPeriod* temp = validity_period_;
  validity_period_ = NULL;
  return temp;
}
inline ::agrirouter::feed::request::ValidityPeriod* MessageDelete::mutable_validity_period() {
  
  if (validity_period_ == NULL) {
    validity_period_ = new ::agrirouter::feed::request::ValidityPeriod;
  }
  // @@protoc_insertion_point(field_mutable:agrirouter.feed.request.MessageDelete.validity_period)
  return validity_period_;
}
inline void MessageDelete::set_allocated_validity_period(::agrirouter::feed::request::ValidityPeriod* validity_period) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete validity_period_;
  }
  if (validity_period) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      validity_period = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, validity_period, submessage_arena);
    }
    
  } else {
    
  }
  validity_period_ = validity_period;
  // @@protoc_insertion_point(field_set_allocated:agrirouter.feed.request.MessageDelete.validity_period)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace request
}  // namespace feed
}  // namespace agrirouter

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messaging_2frequest_2fpayload_2ffeed_2ffeed_2drequests_2eproto__INCLUDED
