// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/response/response.proto

#include "messaging/response/response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace agrirouter {
namespace response {
class ResponseEnvelopeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResponseEnvelope>
      _instance;
} _ResponseEnvelope_default_instance_;
class ResponsePayloadWrapperDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResponsePayloadWrapper>
      _instance;
} _ResponsePayloadWrapper_default_instance_;
}  // namespace response
}  // namespace agrirouter
namespace protobuf_messaging_2fresponse_2fresponse_2eproto {
void InitDefaultsResponseEnvelopeImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_google_2fprotobuf_2ftimestamp_2eproto::InitDefaultsTimestamp();
  {
    void* ptr = &::agrirouter::response::_ResponseEnvelope_default_instance_;
    new (ptr) ::agrirouter::response::ResponseEnvelope();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::agrirouter::response::ResponseEnvelope::InitAsDefaultInstance();
}

void InitDefaultsResponseEnvelope() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsResponseEnvelopeImpl);
}

void InitDefaultsResponsePayloadWrapperImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_google_2fprotobuf_2fany_2eproto::InitDefaultsAny();
  {
    void* ptr = &::agrirouter::response::_ResponsePayloadWrapper_default_instance_;
    new (ptr) ::agrirouter::response::ResponsePayloadWrapper();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::agrirouter::response::ResponsePayloadWrapper::InitAsDefaultInstance();
}

void InitDefaultsResponsePayloadWrapper() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsResponsePayloadWrapperImpl);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponseEnvelope, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponseEnvelope, response_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponseEnvelope, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponseEnvelope, application_message_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponseEnvelope, message_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponseEnvelope, timestamp_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponsePayloadWrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::ResponsePayloadWrapper, details_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::agrirouter::response::ResponseEnvelope)},
  { 10, -1, sizeof(::agrirouter::response::ResponsePayloadWrapper)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::agrirouter::response::_ResponseEnvelope_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::agrirouter::response::_ResponsePayloadWrapper_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "messaging/response/response.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n!messaging/response/response.proto\022\023agr"
      "irouter.response\032\031google/protobuf/any.pr"
      "oto\032\037google/protobuf/timestamp.proto\"\264\003\n"
      "\020ResponseEnvelope\022\025\n\rresponse_code\030\001 \001(\005"
      "\022D\n\004type\030\002 \001(\01626.agrirouter.response.Res"
      "ponseEnvelope.ResponseBodyType\022\036\n\026applic"
      "ation_message_id\030\003 \001(\t\022\022\n\nmessage_id\030\004 \001"
      "(\t\022-\n\ttimestamp\030\005 \001(\0132\032.google.protobuf."
      "Timestamp\"\337\001\n\020ResponseBodyType\022\014\n\010MESSAG"
      "ES\020\000\022\007\n\003ACK\020\001\022\025\n\021ACK_WITH_MESSAGES\020\002\022\024\n\020"
      "ACK_WITH_FAILURE\020\003\022\034\n\030ACK_FOR_FEED_HEADE"
      "R_LIST\020\006\022\030\n\024ACK_FOR_FEED_MESSAGE\020\007\022\037\n\033AC"
      "K_FOR_FEED_FAILED_MESSAGE\020\010\022\025\n\021ENDPOINTS"
      "_LISTING\020\n\022\027\n\023CLOUD_REGISTRATIONS\020\013\"\?\n\026R"
      "esponsePayloadWrapper\022%\n\007details\030\001 \001(\0132\024"
      ".google.protobuf.Anyb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 628);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "messaging/response/response.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2ftimestamp_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_messaging_2fresponse_2fresponse_2eproto
namespace agrirouter {
namespace response {
const ::google::protobuf::EnumDescriptor* ResponseEnvelope_ResponseBodyType_descriptor() {
  protobuf_messaging_2fresponse_2fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_messaging_2fresponse_2fresponse_2eproto::file_level_enum_descriptors[0];
}
bool ResponseEnvelope_ResponseBodyType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 6:
    case 7:
    case 8:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::MESSAGES;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ACK;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ACK_WITH_MESSAGES;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ACK_WITH_FAILURE;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ACK_FOR_FEED_HEADER_LIST;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ACK_FOR_FEED_MESSAGE;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ACK_FOR_FEED_FAILED_MESSAGE;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ENDPOINTS_LISTING;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::CLOUD_REGISTRATIONS;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ResponseBodyType_MIN;
const ResponseEnvelope_ResponseBodyType ResponseEnvelope::ResponseBodyType_MAX;
const int ResponseEnvelope::ResponseBodyType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ResponseEnvelope::InitAsDefaultInstance() {
  ::agrirouter::response::_ResponseEnvelope_default_instance_._instance.get_mutable()->timestamp_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
}
void ResponseEnvelope::clear_timestamp() {
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResponseEnvelope::kResponseCodeFieldNumber;
const int ResponseEnvelope::kTypeFieldNumber;
const int ResponseEnvelope::kApplicationMessageIdFieldNumber;
const int ResponseEnvelope::kMessageIdFieldNumber;
const int ResponseEnvelope::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResponseEnvelope::ResponseEnvelope()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_messaging_2fresponse_2fresponse_2eproto::InitDefaultsResponseEnvelope();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:agrirouter.response.ResponseEnvelope)
}
ResponseEnvelope::ResponseEnvelope(const ResponseEnvelope& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  application_message_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.application_message_id().size() > 0) {
    application_message_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.application_message_id_);
  }
  message_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message_id().size() > 0) {
    message_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_id_);
  }
  if (from.has_timestamp()) {
    timestamp_ = new ::google::protobuf::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = NULL;
  }
  ::memcpy(&response_code_, &from.response_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&response_code_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:agrirouter.response.ResponseEnvelope)
}

void ResponseEnvelope::SharedCtor() {
  application_message_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(type_));
  _cached_size_ = 0;
}

ResponseEnvelope::~ResponseEnvelope() {
  // @@protoc_insertion_point(destructor:agrirouter.response.ResponseEnvelope)
  SharedDtor();
}

void ResponseEnvelope::SharedDtor() {
  application_message_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete timestamp_;
}

void ResponseEnvelope::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ResponseEnvelope::descriptor() {
  ::protobuf_messaging_2fresponse_2fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fresponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResponseEnvelope& ResponseEnvelope::default_instance() {
  ::protobuf_messaging_2fresponse_2fresponse_2eproto::InitDefaultsResponseEnvelope();
  return *internal_default_instance();
}

ResponseEnvelope* ResponseEnvelope::New(::google::protobuf::Arena* arena) const {
  ResponseEnvelope* n = new ResponseEnvelope;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ResponseEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:agrirouter.response.ResponseEnvelope)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  application_message_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
  ::memset(&response_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&response_code_)) + sizeof(type_));
  _internal_metadata_.Clear();
}

bool ResponseEnvelope::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:agrirouter.response.ResponseEnvelope)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 response_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &response_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::agrirouter::response::ResponseEnvelope_ResponseBodyType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string application_message_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_application_message_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->application_message_id().data(), static_cast<int>(this->application_message_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.ResponseEnvelope.application_message_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message_id().data(), static_cast<int>(this->message_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.ResponseEnvelope.message_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp timestamp = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:agrirouter.response.ResponseEnvelope)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:agrirouter.response.ResponseEnvelope)
  return false;
#undef DO_
}

void ResponseEnvelope::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:agrirouter.response.ResponseEnvelope)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 response_code = 1;
  if (this->response_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->response_code(), output);
  }

  // .agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // string application_message_id = 3;
  if (this->application_message_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->application_message_id().data(), static_cast<int>(this->application_message_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.ResponseEnvelope.application_message_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->application_message_id(), output);
  }

  // string message_id = 4;
  if (this->message_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message_id().data(), static_cast<int>(this->message_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.ResponseEnvelope.message_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message_id(), output);
  }

  // .google.protobuf.Timestamp timestamp = 5;
  if (this->has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->timestamp_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:agrirouter.response.ResponseEnvelope)
}

::google::protobuf::uint8* ResponseEnvelope::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:agrirouter.response.ResponseEnvelope)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 response_code = 1;
  if (this->response_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->response_code(), target);
  }

  // .agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // string application_message_id = 3;
  if (this->application_message_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->application_message_id().data(), static_cast<int>(this->application_message_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.ResponseEnvelope.application_message_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->application_message_id(), target);
  }

  // string message_id = 4;
  if (this->message_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message_id().data(), static_cast<int>(this->message_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.ResponseEnvelope.message_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message_id(), target);
  }

  // .google.protobuf.Timestamp timestamp = 5;
  if (this->has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, *this->timestamp_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agrirouter.response.ResponseEnvelope)
  return target;
}

size_t ResponseEnvelope::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agrirouter.response.ResponseEnvelope)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string application_message_id = 3;
  if (this->application_message_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->application_message_id());
  }

  // string message_id = 4;
  if (this->message_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message_id());
  }

  // .google.protobuf.Timestamp timestamp = 5;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->timestamp_);
  }

  // int32 response_code = 1;
  if (this->response_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->response_code());
  }

  // .agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ResponseEnvelope::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:agrirouter.response.ResponseEnvelope)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponseEnvelope* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResponseEnvelope>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:agrirouter.response.ResponseEnvelope)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:agrirouter.response.ResponseEnvelope)
    MergeFrom(*source);
  }
}

void ResponseEnvelope::MergeFrom(const ResponseEnvelope& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:agrirouter.response.ResponseEnvelope)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.application_message_id().size() > 0) {

    application_message_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.application_message_id_);
  }
  if (from.message_id().size() > 0) {

    message_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_id_);
  }
  if (from.has_timestamp()) {
    mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(from.timestamp());
  }
  if (from.response_code() != 0) {
    set_response_code(from.response_code());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void ResponseEnvelope::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:agrirouter.response.ResponseEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponseEnvelope::CopyFrom(const ResponseEnvelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agrirouter.response.ResponseEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponseEnvelope::IsInitialized() const {
  return true;
}

void ResponseEnvelope::Swap(ResponseEnvelope* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResponseEnvelope::InternalSwap(ResponseEnvelope* other) {
  using std::swap;
  application_message_id_.Swap(&other->application_message_id_);
  message_id_.Swap(&other->message_id_);
  swap(timestamp_, other->timestamp_);
  swap(response_code_, other->response_code_);
  swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ResponseEnvelope::GetMetadata() const {
  protobuf_messaging_2fresponse_2fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fresponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ResponsePayloadWrapper::InitAsDefaultInstance() {
  ::agrirouter::response::_ResponsePayloadWrapper_default_instance_._instance.get_mutable()->details_ = const_cast< ::google::protobuf::Any*>(
      ::google::protobuf::Any::internal_default_instance());
}
void ResponsePayloadWrapper::clear_details() {
  if (GetArenaNoVirtual() == NULL && details_ != NULL) {
    delete details_;
  }
  details_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResponsePayloadWrapper::kDetailsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResponsePayloadWrapper::ResponsePayloadWrapper()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_messaging_2fresponse_2fresponse_2eproto::InitDefaultsResponsePayloadWrapper();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:agrirouter.response.ResponsePayloadWrapper)
}
ResponsePayloadWrapper::ResponsePayloadWrapper(const ResponsePayloadWrapper& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_details()) {
    details_ = new ::google::protobuf::Any(*from.details_);
  } else {
    details_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:agrirouter.response.ResponsePayloadWrapper)
}

void ResponsePayloadWrapper::SharedCtor() {
  details_ = NULL;
  _cached_size_ = 0;
}

ResponsePayloadWrapper::~ResponsePayloadWrapper() {
  // @@protoc_insertion_point(destructor:agrirouter.response.ResponsePayloadWrapper)
  SharedDtor();
}

void ResponsePayloadWrapper::SharedDtor() {
  if (this != internal_default_instance()) delete details_;
}

void ResponsePayloadWrapper::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ResponsePayloadWrapper::descriptor() {
  ::protobuf_messaging_2fresponse_2fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fresponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResponsePayloadWrapper& ResponsePayloadWrapper::default_instance() {
  ::protobuf_messaging_2fresponse_2fresponse_2eproto::InitDefaultsResponsePayloadWrapper();
  return *internal_default_instance();
}

ResponsePayloadWrapper* ResponsePayloadWrapper::New(::google::protobuf::Arena* arena) const {
  ResponsePayloadWrapper* n = new ResponsePayloadWrapper;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ResponsePayloadWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:agrirouter.response.ResponsePayloadWrapper)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && details_ != NULL) {
    delete details_;
  }
  details_ = NULL;
  _internal_metadata_.Clear();
}

bool ResponsePayloadWrapper::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:agrirouter.response.ResponsePayloadWrapper)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.protobuf.Any details = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_details()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:agrirouter.response.ResponsePayloadWrapper)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:agrirouter.response.ResponsePayloadWrapper)
  return false;
#undef DO_
}

void ResponsePayloadWrapper::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:agrirouter.response.ResponsePayloadWrapper)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Any details = 1;
  if (this->has_details()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->details_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:agrirouter.response.ResponsePayloadWrapper)
}

::google::protobuf::uint8* ResponsePayloadWrapper::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:agrirouter.response.ResponsePayloadWrapper)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Any details = 1;
  if (this->has_details()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->details_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agrirouter.response.ResponsePayloadWrapper)
  return target;
}

size_t ResponsePayloadWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agrirouter.response.ResponsePayloadWrapper)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .google.protobuf.Any details = 1;
  if (this->has_details()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->details_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ResponsePayloadWrapper::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:agrirouter.response.ResponsePayloadWrapper)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponsePayloadWrapper* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResponsePayloadWrapper>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:agrirouter.response.ResponsePayloadWrapper)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:agrirouter.response.ResponsePayloadWrapper)
    MergeFrom(*source);
  }
}

void ResponsePayloadWrapper::MergeFrom(const ResponsePayloadWrapper& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:agrirouter.response.ResponsePayloadWrapper)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_details()) {
    mutable_details()->::google::protobuf::Any::MergeFrom(from.details());
  }
}

void ResponsePayloadWrapper::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:agrirouter.response.ResponsePayloadWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponsePayloadWrapper::CopyFrom(const ResponsePayloadWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agrirouter.response.ResponsePayloadWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponsePayloadWrapper::IsInitialized() const {
  return true;
}

void ResponsePayloadWrapper::Swap(ResponsePayloadWrapper* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResponsePayloadWrapper::InternalSwap(ResponsePayloadWrapper* other) {
  using std::swap;
  swap(details_, other->details_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ResponsePayloadWrapper::GetMetadata() const {
  protobuf_messaging_2fresponse_2fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fresponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace response
}  // namespace agrirouter

// @@protoc_insertion_point(global_scope)
