// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/response/payload/account/endpoints.proto

#include "messaging/response/payload/account/endpoints.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace agrirouter {
namespace response {
namespace payload {
namespace account {
class ListEndpointsResponse_MessageTypeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListEndpointsResponse_MessageType>
      _instance;
} _ListEndpointsResponse_MessageType_default_instance_;
class ListEndpointsResponse_EndpointDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListEndpointsResponse_Endpoint>
      _instance;
} _ListEndpointsResponse_Endpoint_default_instance_;
class ListEndpointsResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListEndpointsResponse>
      _instance;
} _ListEndpointsResponse_default_instance_;
}  // namespace account
}  // namespace payload
}  // namespace response
}  // namespace agrirouter
namespace protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto {
void InitDefaultsListEndpointsResponse_MessageTypeImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::agrirouter::response::payload::account::_ListEndpointsResponse_MessageType_default_instance_;
    new (ptr) ::agrirouter::response::payload::account::ListEndpointsResponse_MessageType();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::agrirouter::response::payload::account::ListEndpointsResponse_MessageType::InitAsDefaultInstance();
}

void InitDefaultsListEndpointsResponse_MessageType() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsListEndpointsResponse_MessageTypeImpl);
}

void InitDefaultsListEndpointsResponse_EndpointImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse_MessageType();
  {
    void* ptr = &::agrirouter::response::payload::account::_ListEndpointsResponse_Endpoint_default_instance_;
    new (ptr) ::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint::InitAsDefaultInstance();
}

void InitDefaultsListEndpointsResponse_Endpoint() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsListEndpointsResponse_EndpointImpl);
}

void InitDefaultsListEndpointsResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse_Endpoint();
  {
    void* ptr = &::agrirouter::response::payload::account::_ListEndpointsResponse_default_instance_;
    new (ptr) ::agrirouter::response::payload::account::ListEndpointsResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::agrirouter::response::payload::account::ListEndpointsResponse::InitAsDefaultInstance();
}

void InitDefaultsListEndpointsResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsListEndpointsResponseImpl);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_MessageType, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_MessageType, technical_message_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_MessageType, direction_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint, endpoint_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint, endpoint_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint, endpoint_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint, messagetypes_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::agrirouter::response::payload::account::ListEndpointsResponse, endpoints_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::agrirouter::response::payload::account::ListEndpointsResponse_MessageType)},
  { 7, -1, sizeof(::agrirouter::response::payload::account::ListEndpointsResponse_Endpoint)},
  { 17, -1, sizeof(::agrirouter::response::payload::account::ListEndpointsResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::agrirouter::response::payload::account::_ListEndpointsResponse_MessageType_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::agrirouter::response::payload::account::_ListEndpointsResponse_Endpoint_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::agrirouter::response::payload::account::_ListEndpointsResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "messaging/response/payload/account/endpoints.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n2messaging/response/payload/account/end"
      "points.proto\022#agrirouter.response.payloa"
      "d.account\"\354\003\n\025ListEndpointsResponse\022V\n\te"
      "ndpoints\030\001 \003(\0132C.agrirouter.response.pay"
      "load.account.ListEndpointsResponse.Endpo"
      "int\032\206\001\n\013MessageType\022\036\n\026technical_message"
      "_type\030\001 \001(\t\022W\n\tdirection\030\002 \001(\0162D.agrirou"
      "ter.response.payload.account.ListEndpoin"
      "tsResponse.Direction\032\273\001\n\010Endpoint\022\023\n\013end"
      "point_id\030\001 \001(\t\022\025\n\rendpoint_name\030\002 \001(\t\022\025\n"
      "\rendpoint_type\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\022\\\n\014"
      "messageTypes\030\005 \003(\0132F.agrirouter.response"
      ".payload.account.ListEndpointsResponse.M"
      "essageType\"4\n\tDirection\022\010\n\004SEND\020\000\022\013\n\007REC"
      "EIVE\020\001\022\020\n\014SEND_RECEIVE\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 592);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "messaging/response/payload/account/endpoints.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto
namespace agrirouter {
namespace response {
namespace payload {
namespace account {
const ::google::protobuf::EnumDescriptor* ListEndpointsResponse_Direction_descriptor() {
  protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::file_level_enum_descriptors[0];
}
bool ListEndpointsResponse_Direction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ListEndpointsResponse_Direction ListEndpointsResponse::SEND;
const ListEndpointsResponse_Direction ListEndpointsResponse::RECEIVE;
const ListEndpointsResponse_Direction ListEndpointsResponse::SEND_RECEIVE;
const ListEndpointsResponse_Direction ListEndpointsResponse::Direction_MIN;
const ListEndpointsResponse_Direction ListEndpointsResponse::Direction_MAX;
const int ListEndpointsResponse::Direction_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ListEndpointsResponse_MessageType::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListEndpointsResponse_MessageType::kTechnicalMessageTypeFieldNumber;
const int ListEndpointsResponse_MessageType::kDirectionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListEndpointsResponse_MessageType::ListEndpointsResponse_MessageType()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse_MessageType();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
}
ListEndpointsResponse_MessageType::ListEndpointsResponse_MessageType(const ListEndpointsResponse_MessageType& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  technical_message_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.technical_message_type().size() > 0) {
    technical_message_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.technical_message_type_);
  }
  direction_ = from.direction_;
  // @@protoc_insertion_point(copy_constructor:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
}

void ListEndpointsResponse_MessageType::SharedCtor() {
  technical_message_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  direction_ = 0;
  _cached_size_ = 0;
}

ListEndpointsResponse_MessageType::~ListEndpointsResponse_MessageType() {
  // @@protoc_insertion_point(destructor:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  SharedDtor();
}

void ListEndpointsResponse_MessageType::SharedDtor() {
  technical_message_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ListEndpointsResponse_MessageType::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ListEndpointsResponse_MessageType::descriptor() {
  ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ListEndpointsResponse_MessageType& ListEndpointsResponse_MessageType::default_instance() {
  ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse_MessageType();
  return *internal_default_instance();
}

ListEndpointsResponse_MessageType* ListEndpointsResponse_MessageType::New(::google::protobuf::Arena* arena) const {
  ListEndpointsResponse_MessageType* n = new ListEndpointsResponse_MessageType;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ListEndpointsResponse_MessageType::Clear() {
// @@protoc_insertion_point(message_clear_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  technical_message_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  direction_ = 0;
  _internal_metadata_.Clear();
}

bool ListEndpointsResponse_MessageType::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string technical_message_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_technical_message_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->technical_message_type().data(), static_cast<int>(this->technical_message_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.account.ListEndpointsResponse.MessageType.technical_message_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .agrirouter.response.payload.account.ListEndpointsResponse.Direction direction = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_direction(static_cast< ::agrirouter::response::payload::account::ListEndpointsResponse_Direction >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  return false;
#undef DO_
}

void ListEndpointsResponse_MessageType::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string technical_message_type = 1;
  if (this->technical_message_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->technical_message_type().data(), static_cast<int>(this->technical_message_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.MessageType.technical_message_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->technical_message_type(), output);
  }

  // .agrirouter.response.payload.account.ListEndpointsResponse.Direction direction = 2;
  if (this->direction() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->direction(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
}

::google::protobuf::uint8* ListEndpointsResponse_MessageType::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string technical_message_type = 1;
  if (this->technical_message_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->technical_message_type().data(), static_cast<int>(this->technical_message_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.MessageType.technical_message_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->technical_message_type(), target);
  }

  // .agrirouter.response.payload.account.ListEndpointsResponse.Direction direction = 2;
  if (this->direction() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->direction(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  return target;
}

size_t ListEndpointsResponse_MessageType::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string technical_message_type = 1;
  if (this->technical_message_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->technical_message_type());
  }

  // .agrirouter.response.payload.account.ListEndpointsResponse.Direction direction = 2;
  if (this->direction() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->direction());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ListEndpointsResponse_MessageType::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  GOOGLE_DCHECK_NE(&from, this);
  const ListEndpointsResponse_MessageType* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ListEndpointsResponse_MessageType>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
    MergeFrom(*source);
  }
}

void ListEndpointsResponse_MessageType::MergeFrom(const ListEndpointsResponse_MessageType& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.technical_message_type().size() > 0) {

    technical_message_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.technical_message_type_);
  }
  if (from.direction() != 0) {
    set_direction(from.direction());
  }
}

void ListEndpointsResponse_MessageType::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListEndpointsResponse_MessageType::CopyFrom(const ListEndpointsResponse_MessageType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agrirouter.response.payload.account.ListEndpointsResponse.MessageType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListEndpointsResponse_MessageType::IsInitialized() const {
  return true;
}

void ListEndpointsResponse_MessageType::Swap(ListEndpointsResponse_MessageType* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListEndpointsResponse_MessageType::InternalSwap(ListEndpointsResponse_MessageType* other) {
  using std::swap;
  technical_message_type_.Swap(&other->technical_message_type_);
  swap(direction_, other->direction_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ListEndpointsResponse_MessageType::GetMetadata() const {
  protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ListEndpointsResponse_Endpoint::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListEndpointsResponse_Endpoint::kEndpointIdFieldNumber;
const int ListEndpointsResponse_Endpoint::kEndpointNameFieldNumber;
const int ListEndpointsResponse_Endpoint::kEndpointTypeFieldNumber;
const int ListEndpointsResponse_Endpoint::kStatusFieldNumber;
const int ListEndpointsResponse_Endpoint::kMessageTypesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListEndpointsResponse_Endpoint::ListEndpointsResponse_Endpoint()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse_Endpoint();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
}
ListEndpointsResponse_Endpoint::ListEndpointsResponse_Endpoint(const ListEndpointsResponse_Endpoint& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      messagetypes_(from.messagetypes_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  endpoint_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.endpoint_id().size() > 0) {
    endpoint_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endpoint_id_);
  }
  endpoint_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.endpoint_name().size() > 0) {
    endpoint_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endpoint_name_);
  }
  endpoint_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.endpoint_type().size() > 0) {
    endpoint_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endpoint_type_);
  }
  status_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.status().size() > 0) {
    status_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_);
  }
  // @@protoc_insertion_point(copy_constructor:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
}

void ListEndpointsResponse_Endpoint::SharedCtor() {
  endpoint_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endpoint_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endpoint_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

ListEndpointsResponse_Endpoint::~ListEndpointsResponse_Endpoint() {
  // @@protoc_insertion_point(destructor:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  SharedDtor();
}

void ListEndpointsResponse_Endpoint::SharedDtor() {
  endpoint_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endpoint_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endpoint_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ListEndpointsResponse_Endpoint::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ListEndpointsResponse_Endpoint::descriptor() {
  ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ListEndpointsResponse_Endpoint& ListEndpointsResponse_Endpoint::default_instance() {
  ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse_Endpoint();
  return *internal_default_instance();
}

ListEndpointsResponse_Endpoint* ListEndpointsResponse_Endpoint::New(::google::protobuf::Arena* arena) const {
  ListEndpointsResponse_Endpoint* n = new ListEndpointsResponse_Endpoint;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ListEndpointsResponse_Endpoint::Clear() {
// @@protoc_insertion_point(message_clear_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messagetypes_.Clear();
  endpoint_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endpoint_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  endpoint_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ListEndpointsResponse_Endpoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string endpoint_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_endpoint_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->endpoint_id().data(), static_cast<int>(this->endpoint_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string endpoint_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_endpoint_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->endpoint_name().data(), static_cast<int>(this->endpoint_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string endpoint_type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_endpoint_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->endpoint_type().data(), static_cast<int>(this->endpoint_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string status = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_status()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->status().data(), static_cast<int>(this->status().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.status"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .agrirouter.response.payload.account.ListEndpointsResponse.MessageType messageTypes = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_messagetypes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  return false;
#undef DO_
}

void ListEndpointsResponse_Endpoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string endpoint_id = 1;
  if (this->endpoint_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endpoint_id().data(), static_cast<int>(this->endpoint_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->endpoint_id(), output);
  }

  // string endpoint_name = 2;
  if (this->endpoint_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endpoint_name().data(), static_cast<int>(this->endpoint_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->endpoint_name(), output);
  }

  // string endpoint_type = 3;
  if (this->endpoint_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endpoint_type().data(), static_cast<int>(this->endpoint_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->endpoint_type(), output);
  }

  // string status = 4;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), static_cast<int>(this->status().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.status");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->status(), output);
  }

  // repeated .agrirouter.response.payload.account.ListEndpointsResponse.MessageType messageTypes = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->messagetypes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->messagetypes(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
}

::google::protobuf::uint8* ListEndpointsResponse_Endpoint::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string endpoint_id = 1;
  if (this->endpoint_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endpoint_id().data(), static_cast<int>(this->endpoint_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->endpoint_id(), target);
  }

  // string endpoint_name = 2;
  if (this->endpoint_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endpoint_name().data(), static_cast<int>(this->endpoint_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->endpoint_name(), target);
  }

  // string endpoint_type = 3;
  if (this->endpoint_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->endpoint_type().data(), static_cast<int>(this->endpoint_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.endpoint_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->endpoint_type(), target);
  }

  // string status = 4;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), static_cast<int>(this->status().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.status");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->status(), target);
  }

  // repeated .agrirouter.response.payload.account.ListEndpointsResponse.MessageType messageTypes = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->messagetypes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->messagetypes(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  return target;
}

size_t ListEndpointsResponse_Endpoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .agrirouter.response.payload.account.ListEndpointsResponse.MessageType messageTypes = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->messagetypes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->messagetypes(static_cast<int>(i)));
    }
  }

  // string endpoint_id = 1;
  if (this->endpoint_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->endpoint_id());
  }

  // string endpoint_name = 2;
  if (this->endpoint_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->endpoint_name());
  }

  // string endpoint_type = 3;
  if (this->endpoint_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->endpoint_type());
  }

  // string status = 4;
  if (this->status().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ListEndpointsResponse_Endpoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  GOOGLE_DCHECK_NE(&from, this);
  const ListEndpointsResponse_Endpoint* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ListEndpointsResponse_Endpoint>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
    MergeFrom(*source);
  }
}

void ListEndpointsResponse_Endpoint::MergeFrom(const ListEndpointsResponse_Endpoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  messagetypes_.MergeFrom(from.messagetypes_);
  if (from.endpoint_id().size() > 0) {

    endpoint_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endpoint_id_);
  }
  if (from.endpoint_name().size() > 0) {

    endpoint_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endpoint_name_);
  }
  if (from.endpoint_type().size() > 0) {

    endpoint_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.endpoint_type_);
  }
  if (from.status().size() > 0) {

    status_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_);
  }
}

void ListEndpointsResponse_Endpoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListEndpointsResponse_Endpoint::CopyFrom(const ListEndpointsResponse_Endpoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agrirouter.response.payload.account.ListEndpointsResponse.Endpoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListEndpointsResponse_Endpoint::IsInitialized() const {
  return true;
}

void ListEndpointsResponse_Endpoint::Swap(ListEndpointsResponse_Endpoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListEndpointsResponse_Endpoint::InternalSwap(ListEndpointsResponse_Endpoint* other) {
  using std::swap;
  messagetypes_.InternalSwap(&other->messagetypes_);
  endpoint_id_.Swap(&other->endpoint_id_);
  endpoint_name_.Swap(&other->endpoint_name_);
  endpoint_type_.Swap(&other->endpoint_type_);
  status_.Swap(&other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ListEndpointsResponse_Endpoint::GetMetadata() const {
  protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ListEndpointsResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListEndpointsResponse::kEndpointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListEndpointsResponse::ListEndpointsResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:agrirouter.response.payload.account.ListEndpointsResponse)
}
ListEndpointsResponse::ListEndpointsResponse(const ListEndpointsResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      endpoints_(from.endpoints_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:agrirouter.response.payload.account.ListEndpointsResponse)
}

void ListEndpointsResponse::SharedCtor() {
  _cached_size_ = 0;
}

ListEndpointsResponse::~ListEndpointsResponse() {
  // @@protoc_insertion_point(destructor:agrirouter.response.payload.account.ListEndpointsResponse)
  SharedDtor();
}

void ListEndpointsResponse::SharedDtor() {
}

void ListEndpointsResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ListEndpointsResponse::descriptor() {
  ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ListEndpointsResponse& ListEndpointsResponse::default_instance() {
  ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::InitDefaultsListEndpointsResponse();
  return *internal_default_instance();
}

ListEndpointsResponse* ListEndpointsResponse::New(::google::protobuf::Arena* arena) const {
  ListEndpointsResponse* n = new ListEndpointsResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ListEndpointsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:agrirouter.response.payload.account.ListEndpointsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  endpoints_.Clear();
  _internal_metadata_.Clear();
}

bool ListEndpointsResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:agrirouter.response.payload.account.ListEndpointsResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .agrirouter.response.payload.account.ListEndpointsResponse.Endpoint endpoints = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_endpoints()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:agrirouter.response.payload.account.ListEndpointsResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:agrirouter.response.payload.account.ListEndpointsResponse)
  return false;
#undef DO_
}

void ListEndpointsResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:agrirouter.response.payload.account.ListEndpointsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .agrirouter.response.payload.account.ListEndpointsResponse.Endpoint endpoints = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->endpoints_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->endpoints(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:agrirouter.response.payload.account.ListEndpointsResponse)
}

::google::protobuf::uint8* ListEndpointsResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:agrirouter.response.payload.account.ListEndpointsResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .agrirouter.response.payload.account.ListEndpointsResponse.Endpoint endpoints = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->endpoints_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->endpoints(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agrirouter.response.payload.account.ListEndpointsResponse)
  return target;
}

size_t ListEndpointsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agrirouter.response.payload.account.ListEndpointsResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .agrirouter.response.payload.account.ListEndpointsResponse.Endpoint endpoints = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->endpoints_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->endpoints(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ListEndpointsResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:agrirouter.response.payload.account.ListEndpointsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ListEndpointsResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ListEndpointsResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:agrirouter.response.payload.account.ListEndpointsResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:agrirouter.response.payload.account.ListEndpointsResponse)
    MergeFrom(*source);
  }
}

void ListEndpointsResponse::MergeFrom(const ListEndpointsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:agrirouter.response.payload.account.ListEndpointsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  endpoints_.MergeFrom(from.endpoints_);
}

void ListEndpointsResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:agrirouter.response.payload.account.ListEndpointsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListEndpointsResponse::CopyFrom(const ListEndpointsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agrirouter.response.payload.account.ListEndpointsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListEndpointsResponse::IsInitialized() const {
  return true;
}

void ListEndpointsResponse::Swap(ListEndpointsResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListEndpointsResponse::InternalSwap(ListEndpointsResponse* other) {
  using std::swap;
  endpoints_.InternalSwap(&other->endpoints_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ListEndpointsResponse::GetMetadata() const {
  protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messaging_2fresponse_2fpayload_2faccount_2fendpoints_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace account
}  // namespace payload
}  // namespace response
}  // namespace agrirouter

// @@protoc_insertion_point(global_scope)
